### ISSUE TITLE
How can I stop it from prefixing on the svg id

### ISSUE THREAD

**Issue by robertbaker** [jkphl/gulp-svg-sprite#17]
I sort my material-icons as
material-icons/action/*.svg

it adds  "action--" to "ic_[...]_48px" to the id. I don't want them prefixed with the folder name, how can I change that?

**Comment by jkphl** [comment]
Hi @robertbaker, 

all you need to do is use the correct base for your glob, something like this (sorry, untested at the moment):

```javascript
gulp.src('material-icons/action/**/*.svg', {base: 'material-icons/action'})
```

Please let me know if this works for you.

Cheers,
Joschi

**Comment by robertbaker** [comment]
Unless I do multiple src entries, it won't work for me.

```  return gulp.src(options.src + '/assets/material-icons/**/*.svg'  ```

I could also just move the icons to all be in the root folder, but I do like organizing them into their respective category subfolders.

**Comment by jkphl** [comment]
Ah, now I understand what you are after. You will need to alter the `shape.id.generator` callback for this. Given a file structure like this:

```
assets/
|-- a
|   |-- weather-clear.svg
|   `-- weather-overcast.svg
`-- b
    |-- weather-snow.svg
    `-- weather-wind.svg
```

you could use a gulpfile like this:

```js
var gulp				= require('gulp'),
svgSprite				= require('gulp-svg-sprite'),
path					= require('path'),
config					= {
	shape				: {
		id				: {
			generator	: function(name) {
				return path.basename(name, '.svg')
			}
		}
	},
	mode				: {
		css				: {
			prefix		: '.%s',
			dimensions	: false,
			render		: {
				css		: true
			}
		}
	}
};

gulp.task('sprite', function() {
  return gulp.src('**/*.svg', {cwd: 'assets'})
    .pipe(svgSprite(config))
    .pipe(gulp.dest('out'))
});

gulp.task('default', ['sprite']);
```

to get CSS like this:

```css
.weather-clear {
	background: url(svg/sprite.css-49187516.svg) 0 0 no-repeat;
}

.weather-overcast {
	background: url(svg/sprite.css-49187516.svg) 100% 0 no-repeat;
}

.weather-snow {
	background: url(svg/sprite.css-49187516.svg) 0 100% no-repeat;
}

.weather-wind {
	background: url(svg/sprite.css-49187516.svg) 100% 100% no-repeat;
}
```

Is this what you want?
