### ISSUE TITLE
Generated paths in scss file are wrong when using custom template

### ISSUE THREAD

**Issue by StefNet** [jkphl/gulp-svg-sprite#54]
I am using a mustache template to generate a sass map using the svg sprite task. This works fine apart from the fact that the paths are not generated properly in the scss file. At first I just used hardcoded links to the sprite but now I want to use cache busting and can't do that anymore.

My template looks as follows:
```css
$icons: (
    sprite: (width: {{spriteWidth}}px, height: {{spriteHeight}}px, pngPath: '../img/sprite.png', svgPath: '../{{sprite}}'),
{{#shapes}} 	{{base}}: (width: {{width.inner}}px, height: {{height.inner}}px, backgroundX: {{position.absolute.x}}px, backgroundY: {{position.absolute.y}}px),
{{/shapes}});
```

Now the part that goes wrong is svgPath. This will generate:

```css
svgPath: '../img&#x2F;sprite.svg'
```

So it seems its replacing the forward slash with the hex code for a forward slash. 
Any idea how to fix this? Or work around it?
